version: '3'

services:
  mysqldb:
    image: mysql:5.7

    ports:
      - 3307:3306

    volumes:
      - ./var/mysql:/var/lib/mysql

    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}

  web:
    image: nginx

    ports:
      - 10018:80

    volumes:
      - ./config/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/docker/nginx/app.conf:/etc/nginx/conf.d/01-app.conf:ro

  php:
    image: unite/php
